server:
  port: 8011
spring:
  application:
    name: playercenter    # 当前服务注册在 Eureka Server 上的名字
  # 数据库配置
  datasource:
    username: MPCDSEPC
    password: bCHzbS2DTxxXm8Ni
    url: jdbc:mysql://xayytech.com:3306/mpcdsepc
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 162.14.110.70
    port: 6379
    password: lhz20021215
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    mapper-locations: classpath*:**/xml/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # 注册中心的访问地址
  instance:
    prefer-ip-address: true                       # 是否将当前服务ip注册到 Eureka Server

